version: "3.8"

# Development overrides for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reloading
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    command: ["npm", "run", "dev"]

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]

  postgres:
    # Expose port for external access during development
    ports:
      - "5432:5432"
